#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# setup-dh-dec-001.sh
#
# Adds divine-healthcare/06_Decisions/ and DH-DEC-001, and corrects the
# engagement README's artifact table to match DEC-001 (single combined
# standard, DH-STD-002 unallocated).
#
#   usage:  cd ~/downloads/my-portfolio
#           bash ~/downloads/setup-dh-dec-001.sh
#
# Commits but does NOT push.
# ---------------------------------------------------------------------------
set -euo pipefail

git rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
  echo "error: not inside a git repository - cd into your clone first" >&2; exit 1; }

cd "$(git rev-parse --show-toplevel)"

if ! git remote -v | grep -q 'grc-infosec-portfolio'; then
  echo "error: this repo's remote is not grc-infosec-portfolio" >&2
  git remote -v >&2; exit 1
fi

if [ ! -f divine-healthcare/README.md ]; then
  echo "error: divine-healthcare/README.md not found - run the earlier scaffold first" >&2
  exit 1
fi

# Uncommitted files are tolerated here (the local HTML tool lives untracked),
# but anything already staged would get swept into this commit.
if [ -n "$(git diff --cached --name-only)" ]; then
  echo "error: you have staged changes. Commit or unstage them first:" >&2
  git diff --cached --name-only >&2; exit 1
fi

if ! git config user.name >/dev/null || ! git config user.email >/dev/null; then
  echo "error: git identity not set." >&2; exit 1
fi

command -v base64 >/dev/null || { echo "error: base64 not found" >&2; exit 1; }

echo "repo: $(pwd)"
echo

write_file() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  base64 -d > "$path"
  echo "wrote  $path"
}

mkdir -p divine-healthcare/06_Decisions
echo "ready  divine-healthcare/06_Decisions"
echo

write_file 'divine-healthcare/README.md' <<'B64'
IyBEaXZpbmUgSGVhbHRoY2FyZSDigJQgSW5mb3JtYXRpb24gR292ZXJuYW5jZSAmIFJpc2sgUHJv
Z3JhbW1lCgo+ICoqVGhpcyBpcyBhIHNpbXVsYXRlZCBlbmdhZ2VtZW50LioqIERpdmluZSBIZWFs
dGhjYXJlIGlzIGEgZmljdGlvbmFsIDM0MC1iZWQgVVMgaG9zcGl0YWwKPiBjcmVhdGVkIGFzIGEg
c2VsZi1kaXJlY3RlZCBsZWFybmluZyBleGVyY2lzZS4gSXQgaXMgbm90IGEgY2xpZW50IG9yIGFu
IGVtcGxveWVyLCBhbmQgbm8KPiByZWFsIHBhdGllbnQgb3Igb3JnYW5pc2F0aW9uYWwgZGF0YSBh
cHBlYXJzIGFueXdoZXJlIGluIHRoaXMgcHJvamVjdC4gRXZlcnkgYXJ0aWZhY3QgaGVyZQo+IHdh
cyB3cml0dGVuIGJ5IG1lIGZyb20gc2NyYXRjaC4KCioqQXV0aG9yOioqIE1pdGNoZWxsIFN3YXBu
aWwgQ2hhdHRlcmplZQoqKlNlY3RvcjoqKiBIZWFsdGhjYXJlIHByb3ZpZGVyIChVUykKKipQcmlt
YXJ5IHJlZ3VsYXRpb246KiogSElQQUEgU2VjdXJpdHkgUnVsZSBhbmQgUHJpdmFjeSBSdWxlCioq
U3VwcG9ydGluZyBmcmFtZXdvcmtzOioqIE5JU1QgQ1NGIDIuMCwgSVNPL0lFQyAyNzAwMToyMDIy
LCBJU08vSUVDIDI3MDA1OjIwMjIsIE5JU1QgU1AgODAwLTMwIFJldi4gMQoKLS0tCgojIyBXaGF0
IHRoaXMgcHJvamVjdCBpcyBmb3IKCltNZXJpZGlhbiBJbmZvdGVjaF0oLi4vbWVyaWRpYW4taW5m
b3RlY2gvKSBkZW1vbnN0cmF0ZXMgYnJlYWR0aCDigJQgb25lIGNvbnRyb2wgc2V0IG1hcHBlZApz
aW11bHRhbmVvdXNseSBhY3Jvc3MgSVNPIDI3MDAxLCBTT0MgMiwgRFBEUCwgQ0VSVC1JbiwgR0RQ
UiBhbmQgSVNPIDQyMDAxLiBUaGlzIHByb2plY3QKZG9lcyB0aGUgb3Bwb3NpdGUuIEl0IGdvZXMg
ZGVlcCBvbiBhIHNpbmdsZSByZWd1bGF0aW9uLgoKSElQQUEgaXMgdW51c3VhbCBhbW9uZyBzZWN1
cml0eSByZWd1bGF0aW9ucyBiZWNhdXNlIGl0IHNwbGl0cyBpdHMgaW1wbGVtZW50YXRpb24Kc3Bl
Y2lmaWNhdGlvbnMgaW50byAqKlJlcXVpcmVkKiogYW5kICoqQWRkcmVzc2FibGUqKiwgYW5kIGFu
IGFkZHJlc3NhYmxlIHNwZWNpZmljYXRpb24gaXMKbm90IG9wdGlvbmFsIOKAlCBpdCBtdXN0IGJl
IGltcGxlbWVudGVkLCBvciBhIHdyaXR0ZW4ganVzdGlmaWNhdGlvbiBtdXN0IGV4aXN0IGV4cGxh
aW5pbmcgd2h5Cml0IGlzIG5vdCByZWFzb25hYmxlIGFuZCBhcHByb3ByaWF0ZSwgYWxvbmcgd2l0
aCB0aGUgZXF1aXZhbGVudCBhbHRlcm5hdGl2ZSBtZWFzdXJlIGFkb3B0ZWQuCk1vc3Qgb3JnYW5p
c2F0aW9ucyBnZXQgdGhpcyB3cm9uZywgYW5kIGl0IGlzIG9uZSBvZiB0aGUgbW9zdCBjb21tb24g
ZmluZGluZ3MgaW4gT0NSCmVuZm9yY2VtZW50IGFjdGlvbnMuCgpTbyB0aGUgZGVsaXZlcmFibGVz
IGhlcmUgYXJlIGJ1aWx0IHRvIGFuc3dlciBhIHNwZWNpZmljIHF1ZXN0aW9uOiAqKmNhbiB0aGlz
IG9yZ2FuaXNhdGlvbgpwcm9kdWNlIHdyaXR0ZW4gZXZpZGVuY2UgZm9yIGV2ZXJ5IHNhZmVndWFy
ZCBkZWNpc2lvbiBpdCBoYXMgbWFkZT8qKgoKLS0tCgojIyBUaGUgb3JnYW5pc2F0aW9uCgp8IHwg
fAp8LS0tfC0tLXwKfCBTaXplIHwgMzQwIGJlZHMgfAp8IFNlcnZpY2VzIHwgRW1lcmdlbmN5LCBj
bGluaWNhbCB0cmVhdG1lbnQsIGxhYm9yYXRvcnksIHJhZGlvbG9neSwgc3VyZ2VyeSwgcGhhcm1h
Y3ksIGJpbGxpbmcsIGluc3VyYW5jZSBwcm9jZXNzaW5nLCB0ZWxlaGVhbHRoIHwKfCBJbmZvcm1h
dGlvbiBhc3NldHMgfCBlUEhJLCBQSUksIG1lZGljYWwgaW1hZ2luZywgZmluYW5jaWFsIHJlY29y
ZHMsIGVtcGxveWVlIGRhdGEsIGF1ZGl0IGxvZ3MgfAp8IEtub3duIGF1ZGl0IGZpbmRpbmdzIHwg
QVVELTIwMjYtMDExIChubyBzdGFuZGFyZGlzZWQgaGFuZGxpbmcgcmVxdWlyZW1lbnRzKSwgQVVE
LTIwMjYtMDE5IChubyBkb2N1bWVudGVkIGVudGVycHJpc2UgcmlzayBhbmFseXNpcykgfAoKLS0t
CgojIyBBcnRpZmFjdHMKCnwgSUQgfCBBcnRpZmFjdCB8IExvY2F0aW9uIHwgU3RhdHVzIHwKfC0t
LXwtLS18LS0tfC0tLXwKfCBESC1TQ1AtMDAxIHwgU2NvcGUgYW5kIGNvbnRleHQgc3RhdGVtZW50
IHwgYDAwX1Njb3BlL2AgfCBQbGFubmVkIHwKfCBESC1NVEgtMDAxIHwgUmlzayBhc3Nlc3NtZW50
IG1ldGhvZG9sb2d5IHwgYDAxX01ldGhvZG9sb2d5L2AgfCBJbiBwcm9ncmVzcyB8CnwgREgtUlNL
LTAwMSB8IEVudGVycHJpc2UgcmlzayByZWdpc3RlciB8IGAwMl9SZWdpc3RlcnMvYCB8IEluIHBy
b2dyZXNzIHwKfCBESC1CU0wtMDAxIHwgQ29udHJvbCBiYXNlbGluZSByZWdpc3RlciB8IGAwMl9S
ZWdpc3RlcnMvYCB8IFB1Ymxpc2hlZCB8CnwgREgtUE9MLTAwMSB8IEluZm9ybWF0aW9uIGdvdmVy
bmFuY2UgcHJvZ3JhbW1lIHwgYDAzX1BvbGljaWVzL2AgfCBQbGFubmVkIHwKfCBESC1TVEQtMDAx
IHwgSW5mb3JtYXRpb24gY2xhc3NpZmljYXRpb24gYW5kIGhhbmRsaW5nIHN0YW5kYXJkIHwgYDAz
X1BvbGljaWVzL2AgfCBQbGFubmVkIHwKfCBESC1ERUMtMDAxIHwgRGVzaWduIGRlY2lzaW9uIHJl
Y29yZCB8IGAwNl9EZWNpc2lvbnMvYCB8IFB1Ymxpc2hlZCB8CnwgREgtR0FQLTAwMSB8IEhJUEFB
IHNhZmVndWFyZCBnYXAgYXNzZXNzbWVudCB8IGAwNF9Bc3Nlc3NtZW50cy9gIHwgUGxhbm5lZCB8
CgotLS0KCiMjIFRocmVlIGRlY2lzaW9ucyB3b3J0aCBleHBsYWluaW5nCgpQb3J0Zm9saW9zIHVz
dWFsbHkgc2hvdyB0aGUgZmluaXNoZWQgZG9jdW1lbnQuIFRoZXNlIGFyZSB0aGUganVkZ2VtZW50
IGNhbGxzIGJlaGluZCB0aGVtLAp3aGljaCBpcyB3aGF0IEkgd291bGQgd2FudCB0byBiZSBhc2tl
ZCBhYm91dC4KCioqQSBoYW5kbGluZyBtYXRyaXggb2YgYWxsb3dlZCAvIHByb2hpYml0ZWQgZG9l
cyBub3Qgc3Vydml2ZSBjb250YWN0IHdpdGggYSBob3NwaXRhbC4qKgpNeSBmaXJzdCB2ZXJzaW9u
IHByb2hpYml0ZWQgcmVhZGluZyBDb25maWRlbnRpYWwgaW5mb3JtYXRpb24sIHdoaWNoIHdvdWxk
IGhhdmUgc3RvcHBlZApkb2N0b3JzIG9wZW5pbmcgcGF0aWVudCByZWNvcmRzLiBUaGUgcmVzdHJp
Y3Rpb24gaW4gYSBoYW5kbGluZyBzdGFuZGFyZCBpcyBhbG1vc3QgbmV2ZXIgdGhlCmFjdGl2aXR5
IOKAlCBpdCBpcyB3aG8gcGVyZm9ybXMgaXQsIHVuZGVyIHdoYXQgY29uZGl0aW9uLiBUaGF0IHB1
c2hlZCB0aGUgZGVzaWduIHRvd2FyZApjb25kaXRpb25hbCBydWxlcyAoaW50ZXJuYWwgZW1haWwg
cGVybWl0dGVkLCBleHRlcm5hbCBlbWFpbCByZXF1aXJlcyBlbmNyeXB0aW9uKSByYXRoZXIgdGhh
bgpmbGF0IHBlcm1pc3Npb25zLgoKKipBdmFpbGFiaWxpdHkgZmFpbHVyZSBpbiBhIGhvc3BpdGFs
IGlzIGEgcGF0aWVudCBzYWZldHkgZXZlbnQuKioKTG9zcyBvZiBwYXRpZW50IGRhdGEgaXMgc2V2
ZXJlIGFuZCByZWNvdmVyYWJsZS4gTG9zcyBvZiBjbGluaWNhbCBzeXN0ZW1zIG1lYW5zIGFtYnVs
YW5jZQpkaXZlcnNpb24gYW5kIHBhdGllbnRzIHRyYXZlbGxpbmcgZnVydGhlciB0byBjYXJlLCB3
aXRoIG5vIGNsaW5pY2FsIGVycm9yIGFueXdoZXJlIGluIHRoZQpjaGFpbi4gVGhpcyBpcyB3aHkg
dGhlIGltcGFjdCBjcml0ZXJpYSBpbiBESC1NVEgtMDAxIHNjb3JlIHBhdGllbnQgc2FmZXR5IGFz
IGl0cyBvd24KZGltZW5zaW9uIHJhdGhlciB0aGFuIGZvbGRpbmcgaXQgaW50byBvcGVyYXRpb25h
bCBpbXBhY3QsIGFuZCB3aHkgdGhlIG1ldGhvZG9sb2d5IGNhcnJpZXMgYW4Kb3ZlcnJpZGUgcnVs
ZSBlc2NhbGF0aW5nIGFueSBwYXRpZW50LXNhZmV0eS01IHNjZW5hcmlvIHJlZ2FyZGxlc3Mgb2Yg
bGlrZWxpaG9vZC4KCioqQSBjb250cm9sIHRoYXQgZXhpc3RzIGlzIG5vdCBhIGNvbnRyb2wgdGhh
dCB3b3Jrcy4qKgpESC1CU0wtMDAxIHNlcGFyYXRlcyBFdmlkZW5jZWQsIEFzc3VtZWQsIERlZmlu
ZWQtYnV0LW5vdC1lbmZvcmNlZCwgVW5rbm93biBhbmQgQWJzZW50LApiZWNhdXNlIHJlc2lkdWFs
IHJpc2sgbWF5IG9ubHkgY3JlZGl0IGNvbnRyb2xzIHRoYXQgY2FuIGJlIGV2aWRlbmNlZC4gT2Yg
NTYgY29udHJvbHMgaW4gdGhlCmN1cnJlbnQgYmFzZWxpbmUsICoqemVybyBhcmUgZXZpZGVuY2Vk
Kiog4oCUIHdoaWNoIGlzIHRoZSBob25lc3QgcG9zaXRpb24gZm9yIGFuIG9yZ2FuaXNhdGlvbgp0
aGF0IGhhcyBqdXN0IHN0YXJ0ZWQgaXRzIGdvdmVybmFuY2UgcHJvZ3JhbW1lLiBSZWNvcmRpbmcg
dGhhdCBpcyBtb3JlIHVzZWZ1bCB0aGFuIGFzc3VtaW5nCnRoZSBlbnZpcm9ubWVudCBpcyBiZXR0
ZXIgdGhhbiBpdCBpcy4KCi0tLQoKIyMgU2tpbGxzIGRlbW9uc3RyYXRlZAoKLSBISVBBQSBTZWN1
cml0eSBSdWxlIGludGVycHJldGF0aW9uLCBpbmNsdWRpbmcgcmVxdWlyZWQgdnMgYWRkcmVzc2Fi
bGUgc3BlY2lmaWNhdGlvbnMKLSBSaXNrIGFzc2Vzc21lbnQgbWV0aG9kb2xvZ3kgZGVzaWduOiBp
bXBhY3QgYW5kIGxpa2VsaWhvb2QgY3JpdGVyaWEsIGluaGVyZW50IHZzIHJlc2lkdWFsCi0gQ29u
dHJvbCBiYXNlbGluZSBhc3Nlc3NtZW50IHVuZGVyIGluY29tcGxldGUgaW5mb3JtYXRpb24KLSBJ
bmZvcm1hdGlvbiBjbGFzc2lmaWNhdGlvbiBhbmQgY29uZGl0aW9uYWwgaGFuZGxpbmcgcnVsZXMK
LSBEYXRhIG93bmVyc2hpcCwgY3VzdG9kaWFuc2hpcCBhbmQgYWNjb3VudGFiaWxpdHkgbW9kZWxz
Ci0gR292ZXJuYW5jZSBwcm9ncmFtbWUgZGVzaWduIGFuZCBzdGFrZWhvbGRlciBtYXBwaW5nCi0g
RW50ZXJwcmlzZSBzZWN1cml0eSBkb2N1bWVudGF0aW9uIGhpZXJhcmNoeQoKLS0tCgojIyBDb250
YWN0CgpNaXRjaGVsbCBTd2FwbmlsIENoYXR0ZXJqZWUKW2xpbmtlZGluLmNvbS9pbi9taXRjaGVs
bC1jaGF0dGVyamVlLTdhMDQyYjI4N10oaHR0cHM6Ly9saW5rZWRpbi5jb20vaW4vbWl0Y2hlbGwt
Y2hhdHRlcmplZS03YTA0MmIyODcpCm1pdGNoZWxsLnMuY2hhdHRlcmplZUBnbWFpbC5jb20K
B64

write_file 'divine-healthcare/06_Decisions/DH-DEC-001_Design_Decisions.md' <<'B64'
IyBESC1ERUMtMDAxIOKAlCBEZXNpZ24gRGVjaXNpb24gUmVjb3JkCgo+ICoqU2ltdWxhdGVkIGVu
Z2FnZW1lbnQuKiogRGl2aW5lIEhlYWx0aGNhcmUgaXMgYSBmaWN0aW9uYWwgMzQwLWJlZCBVUyBo
b3NwaXRhbCBjcmVhdGVkIGFzIGEKPiBzZWxmLWRpcmVjdGVkIGxlYXJuaW5nIGV4ZXJjaXNlLiBJ
dCBpcyBub3QgYSBjbGllbnQgb3IgYW4gZW1wbG95ZXIsIGFuZCBubyByZWFsIHBhdGllbnQgb3IK
PiBvcmdhbmlzYXRpb25hbCBkYXRhIGFwcGVhcnMgaW4gdGhpcyBkb2N1bWVudC4KCioqQXV0aG9y
OioqIE1pdGNoZWxsIFN3YXBuaWwgQ2hhdHRlcmplZQoqKlZlcnNpb246KiogMS4wCioqT3duZXI6
KiogSW5mb3JtYXRpb24gU2VjdXJpdHkgT2ZmaWNlCgotLS0KCiMjIFB1cnBvc2UKClRoaXMgcmVn
aXN0ZXIgcmVjb3JkcyBkZXNpZ24gZGVjaXNpb25zIHRha2VuIHdoaWxlIGJ1aWxkaW5nIHRoZSBE
aXZpbmUgSGVhbHRoY2FyZSBpbmZvcm1hdGlvbgpzZWN1cml0eSBwcm9ncmFtbWUsIHRoZSByZWFz
b25pbmcgYmVoaW5kIGVhY2gsIGFuZCB0aGUgYWx0ZXJuYXRpdmVzIHJlamVjdGVkLgoKSXQgZXhp
c3RzIGJlY2F1c2UgYSBmaW5pc2hlZCBzdGFuZGFyZCBzaG93cyBvbmx5IGl0cyBjb25jbHVzaW9u
cy4gV2hlbiBhIHJlcXVpcmVtZW50IGlzCmNoYWxsZW5nZWQgZWlnaHRlZW4gbW9udGhzIGxhdGVy
IOKAlCBieSBhbiBhc3Nlc3NvciwgYSBuZXcgYW5hbHlzdCwgb3IgYSBkZXBhcnRtZW50IGhlYWQg
d2hvCmZpbmRzIGl0IGluY29udmVuaWVudCDigJQgdGhlIHF1ZXN0aW9uIGlzIG5ldmVyICp3aGF0
IGRvZXMgaXQgc2F5KiBidXQgKndoeSB3YXMgaXQgd3JpdHRlbiB0aGF0CndheSouIFVuZG9jdW1l
bnRlZCByZWFzb25pbmcgZ2V0cyByZS1saXRpZ2F0ZWQsIGFuZCB1c3VhbGx5IHJldmVyc2VkIGJ5
IHdob2V2ZXIgYXJndWVzIGhhcmRlc3QKcmF0aGVyIHRoYW4gd2hvZXZlciBpcyByaWdodC4KCkVh
Y2ggZGVjaXNpb24gY2FycmllcyBhIHN0YXR1cy4gKipBY2NlcHRlZCoqIG1lYW5zIHRoZSBkZWNp
c2lvbiBpcyBpbiBmb3JjZSBhbmQgZG93bnN0cmVhbQphcnRpZmFjdHMgbXVzdCBjb21wbHkuICoq
UHJvcG9zZWQqKiBtZWFucyBpdCBpcyByZWNvbW1lbmRlZCBidXQgbm90IGNvbmZpcm1lZCwgYW5k
IGFydGlmYWN0cwpzaG91bGQgbm90IHlldCBkZXBlbmQgb24gaXQuICoqU3VwZXJzZWRlZCoqIG1l
YW5zIGEgbGF0ZXIgZGVjaXNpb24gcmVwbGFjZWQgaXQ7IHRoZSByZWNvcmQgaXMKcmV0YWluZWQg
cmF0aGVyIHRoYW4gZGVsZXRlZCwgYmVjYXVzZSB0aGUgcmV2ZXJzYWwgaXMgaXRzZWxmIGluZm9y
bWF0aW9uLgoKLS0tCgojIyBERUMtMDAxIOKAlCBDbGFzc2lmaWNhdGlvbiBhbmQgaGFuZGxpbmcg
cHVibGlzaGVkIGFzIGEgc2luZ2xlIHN0YW5kYXJkCgoqKlN0YXR1czoqKiBBY2NlcHRlZAoKIyMj
IENvbnRleHQKCkVhcmxpZXIgZHJhZnRpbmcgcmVmZXJyZWQgaW5jb25zaXN0ZW50bHkgdG8gYSBj
b21iaW5lZCAqSW5mb3JtYXRpb24gQ2xhc3NpZmljYXRpb24gYW5kCkhhbmRsaW5nIFN0YW5kYXJk
KiAoREgtU1RELTAwMSkgYW5kIHRvIGEgc3BsaXQgcGFpciDigJQgREgtU1RELTAwMSBmb3IgY2xh
c3NpZmljYXRpb24gYW5kCkRILVNURC0wMDIgZm9yIGhhbmRsaW5nLiBCb3RoIGFwcGVhcmVkIGlu
IHdvcmtpbmcgbm90ZXMuIERILVNDUC0wMDEgY3Jvc3MtcmVmZXJlbmNlcyB0aGVzZQpkb2N1bWVu
dHMgYnkgSUQsIHNvIHRoZSBhbWJpZ3VpdHkgaGFkIHRvIGJlIHJlc29sdmVkIGJlZm9yZSBzY29w
ZSB3YXMgaXNzdWVkLgoKIyMjIERlY2lzaW9uCgpDbGFzc2lmaWNhdGlvbiBhbmQgaGFuZGxpbmcg
YXJlIHB1Ymxpc2hlZCBhcyBvbmUgZG9jdW1lbnQsICoqREgtU1RELTAwMSDigJQgSW5mb3JtYXRp
b24KQ2xhc3NpZmljYXRpb24gYW5kIEhhbmRsaW5nIFN0YW5kYXJkKiosIHN0cnVjdHVyZWQgYXMg
YSBib2R5IG9mIHJlcXVpcmVtZW50cyB3aXRoIGZvdXIgYW5uZXhlczoKCnwgfCB8CnwtLS18LS0t
fAp8IEFubmV4IEEgfCBJbmZvcm1hdGlvbiBDbGFzc2lmaWNhdGlvbiBNYXRyaXggfAp8IEFubmV4
IEIgfCBJbmZvcm1hdGlvbiBIYW5kbGluZyBNYXRyaXggfAp8IEFubmV4IEMgfCBUZWNobmljYWwg
RW5mb3JjZW1lbnQgTWF0cml4IHwKfCBBbm5leCBEIHwgSElQQUEgYW5kIE5JU1QgQ1NGIDIuMCBt
YXBwaW5nIHwKCmBESC1TVEQtMDAyYCBpcyBsZWZ0IHVuYWxsb2NhdGVkIGZvciB0aGUgbmV4dCBz
dGFuZGFyZCBpc3N1ZWQsIGV4cGVjdGVkIHRvIGJlIEFjY2VzcyBDb250cm9sLgoKIyMjIFJlYXNv
bmluZwoKQ2xhc3NpZmljYXRpb24gd2l0aG91dCBoYW5kbGluZyBpcyBpbmVydC4gQSBkb2N1bWVu
dCBkZWZpbmluZyBmb3VyIHNlbnNpdGl2aXR5IGxldmVscyBhbmQKc3RvcHBpbmcgdGhlcmUgdGVs
bHMgdGhlIHJlYWRlciB3aGF0IGluZm9ybWF0aW9uIGlzIHdvcnRoIGFuZCBub3RoaW5nIGFib3V0
IHdoYXQgdG8gZG8gd2l0aAppdDsgdGhlIGhhbmRsaW5nIHJ1bGVzIGFyZSB3aGF0IGdpdmUgdGhl
IGxldmVscyBjb25zZXF1ZW5jZS4KClRoZSB0d28gYXJlIGFsc28gc3RydWN0dXJhbGx5IHRoZSBz
YW1lIGFydGlmYWN0LiBUaGUgcm93cyBvZiB0aGUgaGFuZGxpbmcgbWF0cml4IGFyZSB0aGUKY2xh
c3NpZmljYXRpb24gbGV2ZWxzLiBQdWJsaXNoaW5nIHRoZW0gc2VwYXJhdGVseSBwbGFjZXMgdGhl
IHNhbWUgdGF4b25vbXkgaW4gdHdvIGRvY3VtZW50cwp0aGF0IG11c3QgYWdyZWUsIGFuZCB2ZXJz
aW9uIGRyaWZ0IGJldHdlZW4gZG9jdW1lbnRzIHRoYXQgbXVzdCBhZ3JlZSBpcyBhIHJlY3Vycmlu
ZyBhdWRpdApmaW5kaW5nLgoKT3BlcmF0aW9uYWxseSwgYSBjbGluaWNpYW4gZGVjaWRpbmcgd2hh
dCBtYXkgYmUgZG9uZSB3aXRoIGFuIGltYWdpbmcgcmVwb3J0IHNob3VsZCBjb25zdWx0IG9uZQpk
b2N1bWVudCwgbm90IHR3by4KCiMjIyBBbHRlcm5hdGl2ZXMgY29uc2lkZXJlZAoKKipTcGxpdCBp
bnRvIHR3byBzdGFuZGFyZHMuKiogQXBwcm9wcmlhdGUgd2hlcmUgaGFuZGxpbmcgZ3Jvd3MgaW50
byBwZXItY2hhbm5lbCBhbmQgcGVyLW1lZGlhCmFubmV4ZXMgcnVubmluZyB0byBkb3plbnMgb2Yg
cGFnZXMsIG9yIHdoZXJlIGNsYXNzaWZpY2F0aW9uIGlzIG93bmVkIGJ5IGEgZGF0YSBnb3Zlcm5h
bmNlCmZ1bmN0aW9uIGFuZCBoYW5kbGluZyBieSBzZWN1cml0eSBvcGVyYXRpb25zLiBEaXZpbmUg
SGVhbHRoY2FyZSBoYXMgbmVpdGhlciBjb25kaXRpb246IGEKc2luZ2xlIGluZm9ybWF0aW9uIHNl
Y3VyaXR5IG9mZmljZSBvd25zIGJvdGgsIGFuZCB0aGUgY29tYmluZWQgZG9jdW1lbnQgaXMgZXhw
ZWN0ZWQgdG8gcnVuCndlbGwgdW5kZXIgdGhpcnR5IHBhZ2VzIGluY2x1ZGluZyBhbm5leGVzLgoK
IyMjIENvbnNlcXVlbmNlcwoKLSBESC1TQ1AtMDAxIHJlZmVyZW5jZXMgREgtU1RELTAwMSBvbmx5
LiBObyByZWZlcmVuY2UgdG8gREgtU1RELTAwMiB1bnRpbCBhIHN0YW5kYXJkIGlzIGlzc3VlZAog
IHVuZGVyIHRoYXQgbnVtYmVyLgotIEFubmV4ZXMgYXJlIHNlcGFyYXRlbHkgdmVyc2lvbmVkLCBz
byBBbm5leCBCIG9yIEMgbWF5IGJlIHJlaXNzdWVkIHdpdGhvdXQgcmVvcGVuaW5nIHRoZQogIGNs
YXNzaWZpY2F0aW9uIG1vZGVsLCB3aGljaCBpcyBleHBlY3RlZCB0byByZW1haW4gc3RhYmxlIGZv
ciB5ZWFycy4KLSBBbm5leCBDIGluaGVyaXRzIGEgZGVwZW5kZW5jeSBvbiBERUMtMDAzIGJlbG93
LgoKLS0tCgojIyBERUMtMDAyIOKAlCBSZXF1aXJlbWVudHMgYXJlIHZlbmRvci1uZXV0cmFsOyB0
ZWNobm9sb2d5IGlzIGNvbmZpbmVkIHRvIEFubmV4IEMKCioqU3RhdHVzOioqIEFjY2VwdGVkCgoj
IyMgQ29udGV4dAoKTWljcm9zb2Z0IFB1cnZpZXcgaXMgdGhlIGFzc3VtZWQgZW5mb3JjZW1lbnQg
cGxhdGZvcm0gZm9yIGluZm9ybWF0aW9uIHByb3RlY3Rpb24gd2l0aGluIHRoZQpNaWNyb3NvZnQg
MzY1IGVzdGF0ZS4gVGhlIHF1ZXN0aW9uIHdhcyB3aGV0aGVyIG5hbWVkIHByb2R1Y3RzIG1heSBh
cHBlYXIgaW5zaWRlIHRoZQpzdGFuZGFyZCdzIG51bWJlcmVkIHJlcXVpcmVtZW50cy4KCiMjIyBE
ZWNpc2lvbgoKUmVxdWlyZW1lbnRzIGluIHRoZSBib2R5IG9mIERILVNURC0wMDEgc3RhdGUgb3V0
Y29tZXMgd2l0aG91dCBuYW1pbmcgcHJvZHVjdHMuIE5hbWVkCnRlY2hub2xvZ3kgYXBwZWFycyBv
bmx5IGluICoqQW5uZXggQyDigJQgVGVjaG5pY2FsIEVuZm9yY2VtZW50IE1hdHJpeCoqLCB3aGlj
aCBtYXBzIGVhY2gKcmVxdWlyZW1lbnQgdG8gdGhlIG1lY2hhbmlzbSBjdXJyZW50bHkgZW5mb3Jj
aW5nIGl0LgoKQ29ycmVjdDoKCj4gKio1LjQqKiBJbmZvcm1hdGlvbiBjbGFzc2lmaWVkIFJlc3Ry
aWN0ZWQgc2hhbGwgYmUgZW5jcnlwdGVkIHdoZW4gdHJhbnNtaXR0ZWQgb3V0c2lkZSB0aGUKPiBE
aXZpbmUgSGVhbHRoY2FyZSBuZXR3b3JrLgoKSW5jb3JyZWN0OgoKPiAqKjUuNCoqIEluZm9ybWF0
aW9uIGNsYXNzaWZpZWQgUmVzdHJpY3RlZCBzaGFsbCBiZSBlbmNyeXB0ZWQgdXNpbmcgTWljcm9z
b2Z0IFB1cnZpZXcgTWVzc2FnZQo+IEVuY3J5cHRpb24gd2hlbiB0cmFuc21pdHRlZCBvdXRzaWRl
IHRoZSBEaXZpbmUgSGVhbHRoY2FyZSBuZXR3b3JrLgoKIyMjIFJlYXNvbmluZwoKQSByZXF1aXJl
bWVudCBuYW1pbmcgYSBwcm9kdWN0IG11c3QgYmUgcmVpc3N1ZWQgd2hlbiB0aGUgcHJvZHVjdCBj
aGFuZ2VzLCBhbmQgaXMKdW5lbmZvcmNlYWJsZSBpbiBhbnkgc3lzdGVtIHRoZSBwcm9kdWN0IGRv
ZXMgbm90IGNvdmVyLiBJbiBhIGhvc3BpdGFsIHRoaXMgaXMgbW9zdCBzeXN0ZW1zOgpQdXJ2aWV3
IG9wZXJhdGVzIHdpdGhpbiBNaWNyb3NvZnQgMzY1IGFuZCBoYXMgbm8gdmlzaWJpbGl0eSBpbnRv
IHRoZSBFSFIsIFBBQ1MsIHRoZSBsYWJvcmF0b3J5CmluZm9ybWF0aW9uIHN5c3RlbSwgYmlsbGlu
Zywgb3IgbmV0d29ya2VkIG1lZGljYWwgZGV2aWNlcy4gQSBzdGFuZGFyZCB3aG9zZSByZXF1aXJl
bWVudHMKYXNzdW1lIFB1cnZpZXcgd291bGQgdGhlcmVmb3JlIGJlIHVuZW5mb3JjZWFibGUgYWNy
b3NzIHRoZSBtYWpvcml0eSBvZiB0aGUgZXN0YXRlIGhvbGRpbmcgdGhlCm9yZ2FuaXNhdGlvbidz
IG1vc3Qgc2Vuc2l0aXZlIGluZm9ybWF0aW9uLgoKVGhpcyBhbHNvIHByZXNlcnZlcyB0aGUgZG9j
dW1lbnRhdGlvbiBoaWVyYXJjaHkuIEEgc3RhbmRhcmQgZGVmaW5lcyBob3cgY29uc2lzdGVuY3kg
aXMKYWNoaWV2ZWQ7IHRoZSBtZWNoYW5pc20gdGhhdCBhY2hpZXZlcyBpdCBiZWxvbmdzIG9uZSBs
YXllciBkb3duLgoKIyMjIENvbnNlcXVlbmNlcwoKLSBBbm5leCBDIG1hcHMgcmVxdWlyZW1lbnRz
IHRvIGVuZm9yY2VtZW50IG1lY2hhbmlzbXMgYWNyb3NzIHRoZSB3aG9sZSBlc3RhdGUsIG5vdCBv
bmx5CiAgTWljcm9zb2Z0IDM2NS4gQ2xpbmljYWwgc3lzdGVtcyBtYXAgdG8gdGhlaXIgb3duIG5h
dGl2ZSBhY2Nlc3MgY29udHJvbHMuCi0gQW5uZXggQyBjYXJyaWVzIGEgKipzdGF0ZSoqIHF1YWxp
ZmllciBwZXIgcm93LCBkaXN0aW5ndWlzaGluZyBsaWNlbnNlZCwgZGVwbG95ZWQsIGNvbmZpZ3Vy
ZWQsCiAgYW5kIG9wZXJhdGluZy13aXRoLWV2aWRlbmNlLiBPbmx5IHRoZSBsYXN0IGNvbnN0aXR1
dGVzIGEgY29udHJvbCBmb3IgdGhlIHB1cnBvc2VzIG9mCiAgREgtQlNMLTAwMSBhbmQgcmVzaWR1
YWwgcmlzayBzY29yaW5nIGluIERILVJTSy0wMDEuCi0gQW5uZXggQyBtdXN0IHJlbWFpbiBjb25z
aXN0ZW50IHdpdGggREgtQlNMLTAwMS4gV2hlcmUgdGhlIGJhc2VsaW5lIHJlY29yZHMgYSBjb250
cm9sIGFzCiAgYWJzZW50IG9yIHVudmVyaWZpZWQsIEFubmV4IEMgZGVzY3JpYmVzIHRhcmdldCBz
dGF0ZSBhbmQgbXVzdCBzYXkgc28gZXhwbGljaXRseS4KCi0tLQoKIyMgREVDLTAwMyDigJQgQXNz
dW1lZCBsaWNlbnNpbmcgYmFzZWxpbmUgZXhjbHVkZXMgdGhlIE1pY3Jvc29mdCAzNjUgY29tcGxp
YW5jZSBzdGFjawoKKipTdGF0dXM6KiogUHJvcG9zZWQKCiMjIyBDb250ZXh0CgpBbm5leCBDIGNh
bm5vdCBiZSBkcmFmdGVkIHdpdGhvdXQgYSBwb3NpdGlvbiBvbiB3aGF0IERpdmluZSBIZWFsdGhj
YXJlIGlzIGxpY2Vuc2VkIGZvci4gVGhlCk1pY3Jvc29mdCBQdXJ2aWV3IGNhcGFiaWxpdHkgc2V0
IGlzIHNwbGl0IGFjcm9zcyBsaWNlbmNlIHRpZXJzLCBhbmQgc2V2ZXJhbCBjb250cm9scyByZWxl
dmFudAp0byB0aGUgZmluZGluZ3MgaW4gQVVELTIwMjYtMDExIHNpdCBhYm92ZSB0aGUgYmFzZSB0
aWVyLgoKIyMjIERlY2lzaW9uIChwcm9wb3NlZCkKCkRpdmluZSBIZWFsdGhjYXJlIGlzIGFzc3Vt
ZWQgdG8gaG9sZCBNaWNyb3NvZnQgMzY1IEUzIG9yIEJ1c2luZXNzIFByZW1pdW0gKip3aXRob3V0
KiogdGhlIEU1CkNvbXBsaWFuY2Ugb3IgRTUgU2VjdXJpdHkgYWRkLW9ucy4KClVuZGVyIHRoYXQg
YXNzdW1wdGlvbjoKCnwgQ2FwYWJpbGl0eSB8IEF2YWlsYWJpbGl0eSB8CnwtLS18LS0tfAp8IE1h
bnVhbCBzZW5zaXRpdml0eSBsYWJlbHMgd2l0aCBlbmNyeXB0aW9uIHwgQXZhaWxhYmxlIHwKfCBE
TFAgZm9yIEV4Y2hhbmdlLCBTaGFyZVBvaW50LCBPbmVEcml2ZSB8IEF2YWlsYWJsZSB8CnwgQXVk
aXQgbG9nIHJldGVudGlvbiAoOTAgZGF5cykgfCBBdmFpbGFibGUgfAp8IEF1dG9tYXRpYyBhbmQg
cG9saWN5LWJhc2VkIGxhYmVsbGluZyB8IFJlcXVpcmVzIEU1IG9yIEluZm9ybWF0aW9uIFByb3Rl
Y3Rpb24gYW5kIEdvdmVybmFuY2UgYWRkLW9uIHwKfCBFbmRwb2ludCBETFAgKHByaW50LCBjbGlw
Ym9hcmQsIHJlbW92YWJsZSBtZWRpYSkgfCBSZXF1aXJlcyBFNSBvciBQdXJ2aWV3IERMUCBhZGQt
b24gfAp8IERMUCBmb3IgVGVhbXMgY2hhdCB8IFJlcXVpcmVzIEU1IHwKfCBETFAgc2ltdWxhdGlv
biBtb2RlIHwgUmVxdWlyZXMgRTUgQ29tcGxpYW5jZSB8CnwgRGVmZW5kZXIgZm9yIENsb3VkIEFw
cHMgfCBSZXF1aXJlcyBFNSBvciBFNSBTZWN1cml0eSBhZGQtb24g4oCUICoqbm90KiogaW5jbHVk
ZWQgaW4gRTUgQ29tcGxpYW5jZSB8CgojIyMgQ29uc2VxdWVuY2VzIGZvciBBVUQtMjAyNi0wMTEK
CnwgRmluZGluZyB8IFBvc2l0aW9uIHVuZGVyIHRoaXMgYmFzZWxpbmUgfAp8LS0tfC0tLXwKfCBV
bmVuY3J5cHRlZCBpbnRlcm5hbCBwYXRpZW50IGVtYWlsIHwgUmVtZWRpYWJsZSDigJQgRXhjaGFu
Z2UgRExQIGFuZCBtZXNzYWdlIGVuY3J5cHRpb24gYXZhaWxhYmxlIHwKfCBSZXNlYXJjaCBkYXRh
IGluIHBlcnNvbmFsIE9uZURyaXZlIHwgUGFydGlhbCDigJQgc2FuY3Rpb25lZCB0ZW5hbnQgZ292
ZXJuYWJsZTsgdW5zYW5jdGlvbmVkIGNsb3VkIHJlcXVpcmVzIERlZmVuZGVyIGZvciBDbG91ZCBB
cHBzIHwKfCBVbnJlc3RyaWN0ZWQgcHJpbnRpbmcgb2Ygc2FsYXJ5IGRhdGEgfCBOb3QgcmVtZWRp
YWJsZSDigJQgcmVxdWlyZXMgRW5kcG9pbnQgRExQIHwKfCBNUkkgaW1hZ2VzIG9uIGxvY2FsIGRl
c2t0b3BzIHwgTm90IHJlbWVkaWFibGUg4oCUIHJlcXVpcmVzIEVuZHBvaW50IERMUCB8CnwgQXVk
aXQgbG9ncyBjb3BpZWQgdG8gcmVtb3ZhYmxlIG1lZGlhIHwgTm90IHJlbWVkaWFibGUg4oCUIHJl
cXVpcmVzIEVuZHBvaW50IERMUCB8CgpUaHJlZSBvZiBmaXZlIGF1ZGl0IGZpbmRpbmdzIGhhdmUg
bm8gYXZhaWxhYmxlIHRlY2huaWNhbCBlbmZvcmNlbWVudCBtZWNoYW5pc20gYXQgdGhpcwpsaWNl
bnNpbmcgcG9zaXRpb24uCgojIyMgUmVhc29uaW5nCgpUaGlzIGJhc2VsaW5lIGlzIGNob3NlbiBk
ZWxpYmVyYXRlbHkgb3ZlciB0aGUgYWx0ZXJuYXRpdmUsIHdoaWNoIHdvdWxkIGFzc3VtZSB0aGUg
Y29tcGxpYW5jZQpzdGFjayBpcyBsaWNlbnNlZCBidXQgdW5jb25maWd1cmVkLgoKVW5kZXIgdGhl
IGFsdGVybmF0aXZlLCBldmVyeSByZXF1aXJlbWVudCBtYXBzIGNsZWFubHkgdG8gYW4gYXZhaWxh
YmxlIE1pY3Jvc29mdCBjYXBhYmlsaXR5IGFuZAp0aGUgcmVtZWRpYXRpb24gZ2FwIGlzIGNvbmZp
Z3VyYXRpb24gYW5kIHJvbGxvdXQuIFRoYXQgcHJvZHVjZXMgYSB0aWRpZXIgYW5uZXggYW5kIGEg
d2Vha2VyCmRvY3VtZW50LiBJdCBhbHNvIGludml0ZXMgYSBzcGVjaWZpYyBlcnJvcjogY3JlZGl0
aW5nIGNvbnRyb2xzIHRoYXQgYXJlIGxpY2Vuc2VkIGJ1dCBub3QKb3BlcmF0aW5nLCB3aGljaCBp
cyBwcmVjaXNlbHkgdGhlIGRpc3RpbmN0aW9uIERILUJTTC0wMDEgZXhpc3RzIHRvIGVuZm9yY2Uu
CgpUaGUgcHJvcG9zZWQgYmFzZWxpbmUgZm9yY2VzIHRocmVlIHRoaW5ncyBhIGxpY2Vuc2VkLWJ1
dC11bmNvbmZpZ3VyZWQgYXNzdW1wdGlvbiBkb2VzIG5vdC4KUmVxdWlyZW1lbnRzIHdpdGhvdXQg
dGVjaG5pY2FsIGVuZm9yY2VtZW50IG11c3QgYmUgc3VwcG9ydGVkIGJ5IGNvbXBlbnNhdGluZyBh
ZG1pbmlzdHJhdGl2ZQpjb250cm9scyDigJQgcHJvY2VkdXJlLCB0cmFpbmluZywgYW5kIG1vbml0
b3Jpbmcg4oCUIHdpdGggdGhlaXIgd2Vha25lc3Mgc3RhdGVkIHJhdGhlciB0aGFuCmNvbmNlYWxl
ZC4gVGhlIHVucmVtZWRpYWJsZSBmaW5kaW5ncyBtdXN0IGJlIGFzc2VtYmxlZCBpbnRvIGEgY29z
dGVkIHByb2N1cmVtZW50IGNhc2UgdGllZCB0bwpuYW1lZCBhdWRpdCBmaW5kaW5ncy4gQW5kIHRo
ZSByZXNpZHVhbCByaXNrIHBvc2l0aW9uIHN0YXlzIGNvbnNpc3RlbnQgd2l0aCBESC1CU0wtMDAx
LCB3aGljaApjdXJyZW50bHkgcmVjb3JkcyB6ZXJvIGV2aWRlbmNlZCBjb250cm9scy4KCkEgc2Vj
b25kYXJ5IGNvbnNpZGVyYXRpb246IEUzIERMUCBoYXMgbm8gc2ltdWxhdGlvbiBtb2RlLCBzbyBh
bnkgcG9saWN5IGRlcGxveWVkIGdvZXMgZGlyZWN0bHkKdG8gZW5mb3JjZW1lbnQuIEluIGEgY2xp
bmljYWwgZW52aXJvbm1lbnQsIGFuIHVudGVzdGVkIERMUCBwb2xpY3kgYmxvY2tpbmcgbGVnaXRp
bWF0ZSBjYXJlCmNvbW11bmljYXRpb24gaXMgYW4gYXZhaWxhYmlsaXR5IHJpc2sgd2l0aCBwYXRp
ZW50IHNhZmV0eSBjb25zZXF1ZW5jZXMuIFRoZSBzdGFuZGFyZCBtdXN0CnJlcXVpcmUgcGhhc2Vk
IGRlcGxveW1lbnQgYXMgYSBjb21wZW5zYXRpbmcgbWVhc3VyZSBmb3IgdGhlIG1pc3NpbmcgY2Fw
YWJpbGl0eS4KCiMjIyBPcGVuCgpUaGlzIGRlY2lzaW9uIGlzICoqUHJvcG9zZWQqKiwgbm90IEFj
Y2VwdGVkLiBDb25maXJtYXRpb24gaXMgcmVxdWlyZWQgYmVmb3JlIEFubmV4IEMgaXMKZHJhZnRl
ZC4gSWYgdGhlIGxpY2Vuc2luZyBwb3NpdGlvbiBjaGFuZ2VzLCB0aGlzIHJlY29yZCBpcyBzdXBl
cnNlZGVkIHJhdGhlciB0aGFuIGVkaXRlZCwgYW5kCkFubmV4IEMgaXMgcmVpc3N1ZWQgYWdhaW5z
dCB0aGUgbmV3IGJhc2VsaW5lLgoKLS0tCgojIyBSZXZpc2lvbiBoaXN0b3J5Cgp8IFZlcnNpb24g
fCBEYXRlIHwgQ2hhbmdlIHwKfC0tLXwtLS18LS0tfAp8IDEuMCB8IOKAlCB8IEluaXRpYWwgaXNz
dWUuIERFQy0wMDEgYW5kIERFQy0wMDIgYWNjZXB0ZWQ7IERFQy0wMDMgcHJvcG9zZWQuIHwK
B64

echo

# Stage only the two paths this script touches, so nothing else is swept in.
git add divine-healthcare/README.md divine-healthcare/06_Decisions

echo "=== staged changes ==="
git status --short -- divine-healthcare/README.md divine-healthcare/06_Decisions
echo

git commit -q -F - <<'MSG'
Add DH-DEC-001 design decision record; correct standard numbering

Records three design decisions with reasoning and rejected alternatives,
so the rationale behind DH-STD-001 survives independently of the standard
itself.

DEC-001 (accepted) - classification and handling publish as one standard,
DH-STD-001, with four annexes. Resolves an inconsistency in working notes
that had DH-STD-001/002 as a split pair. DH-STD-002 left unallocated.

DEC-002 (accepted) - requirements stay vendor-neutral; named technology is
confined to Annex C. Purview operates only within Microsoft 365 and cannot
reach the EHR, PACS, LIS, billing or medical devices, so product-named
requirements would be unenforceable across most of the estate.

DEC-003 (proposed) - assumed licensing baseline excludes the M365
compliance stack, leaving three of five AUD-2026-011 findings without
technical enforcement. Forces compensating controls and a costed
procurement case rather than a clean product map. Awaiting confirmation
before Annex C is drafted.

README artifact table corrected to match DEC-001.
MSG

echo "=== commit ==="
git log --oneline -1
git show --stat --oneline HEAD | tail -n +2
echo
echo "Nothing has been pushed. Review, then run: git push"
